#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute alpha diversity
echo "Computing alpha diversity"
parallel_alpha_diversity.py \
-i /home/cbmucl06/Combo_analysis/Alpha_analysis/Rarefied_tables_e4284 \
-o /home/cbmucl06/Combo_analysis/Alpha_analysis/Simpson_tables_e4284 \
-t /home/cbmucl06/Combo_analysis/Composition_analysis/combo_filtered_rep_phylogeny.tre \
-m shannon,PD_whole_tree,chao1,observed_otus,goods_coverage \
-O 24


#Deactivating environment
source deactivate
