#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Splitting libraries
echo "Split libraries"
split_libraries_fastq.py \
-i ~/SeqPrep_joined/seqprep_assembled.fastq.gz \
-b ~/SeqPrep_joined/seqprep_assembled.fastq_barcodes.fastq \
-o ~/Split_libraries_Q25_qual \
-m ~/Raw_data/Park_data/map_complete.tsv \
-q 24 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes \
--store_qual_scores

#Deactivating environment
source deactivate
