#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter chimeric sequences
echo "Filtering chimeras"
filter_fasta.py \
-f /home/cbmucl06/Combo_analysis/merged.fna \
-o /home/cbmucl06/Combo_analysis/chimera_free_combo_seqs.fna \
-s /home/cbmucl06/Combo_analysis/Chimeric_seqs/chimeras.txt \
-n

echo "Filtering fasta sequences...completed."
