#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Align representative sequences
echo "Aligning representative sequences"
align_seqs.py \
-i /home/cbmucl06/Combo_analysis/filtered_combo_rep_set.fna \
-o /home/cbmucl06/Combo_analysis/Aligned_filtered_combo_rep_set \
-t ~/SILVA_database/97_alignment.fna

#Deactivating environment
source deactivate
