#!/bin/bash
#SBATCH -t 0:20:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Align representative sequences
echo "Aligning representative sequences"
align_seqs.py \
-i /home/cbmucl06/Combo_analysis/combo_rep_set.fna \
-o /home/cbmucl06/Combo_analysis/pynast_combo_aligned_rep_set \
-t ~/SILVA_database/97_alignment.fna

#Deactivating environment
source deactivate
