#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Align representative sequences
echo "Aligning representative sequences"
align_seqs.py \
-i /home/cbmucl06/Split_libraries_Q25_farm/seqs.fna \
-o /home/cbmucl06/Aligned_repr_seqs_farm \
-t ~/SILVA_database/97_alignment.fna

#Deactivating environment
source deactivate
