#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Parallel alpha diversoty
echo "Calculating alpha diversity"
parallel_alpha_diversity.py \
-i /home/cbmucl06/Picked_OTUs/Close_ref_otus_Q25_contax7/Rarefied_otu_tables/
-o /home/cbmucl06/Picked_OTUs/Close_ref_otus_Q25_contax7/Alpha_div_rarefied_tables
-t ~/SILVA_database/97_otus.tre \
-m observed_otus,chao1,PD_whole_tree,goods_coverage \
-O 24

#Deactivating environment
source deactivate
