#!/bin/bash
#SBATCH -t 2:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute beta diversity
echo "Computing beta diversity"
parallel_beta_diversity.py \
-i /home/cbmucl06/Combo_analysis/Alpha_analysis/Rarefied_tables_e4141 \
-o /home/cbmucl06/Combo_analysis/Beta_analysis \
--metrics unweighted_unifrac,weighted_unifrac,bray_curtis \
-t /home/cbmucl06/Combo_analysis/Composition_analysis/combo_filtered_rep_phylogeny.tre \
-O 24

#Deactivating environment
source deactivate
