#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute beta diversity
echo "Computing beta diversity"
beta_diversity_through_plots.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom \
-o ~/Combo_analysis/Beta_analysis/ \
-t /home/cbmucl06/Combo_analysis/Composition_analysis/combo_filtered_rep_phylogeny.tre \
-m ~/Raw_data/merged_map_no_conv.tsv \
-e 4284 \
-p ~/Parameter_files/beta_div.txt

#Deactivating environment
source deactivate
