#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute beta diversity
echo "Computing beta diversity"
beta_diversity_through_plots.py \
-i /home/cbmucl06/Combo_analysis/PICRUSt_analysis/BIOM_tables/PICRUSt_highlev_BIOM.biom \
-o ~/Combo_analysis/PICRUSt_analysis/Beta_diversity_hilev \
-m ~/Raw_data/merged_map_no_conv.tsv \
-e 5590398 \
-p ~/Parameter_files/picrust.txt

#Deactivating environment
source deactivate
