#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Collate alpha results
echo "Collating alpha diversity"
collate_alpha.py \
-i /home/cbmucl06/Combo_analysis/Alpha_analysis/Alpha_tables_e4284 \
-o /home/cbmucl06/Combo_analysis/Alpha_analysis/Collated_alpha_analysis_e4284

#Deactivating environment
source deactivate
