#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Collate alpha results
echo "Collating alpha diversity"
collate_alpha.py \
-i /home/cbmucl06/Close_ref_otus_chimerafree/Alpha_div_rarefied_tables \
-o /home/cbmucl06/Close_ref_otus_chimerafree/Results/Collated_alpha_analysis \

#Deactivating environment
source deactivate
