#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compare categories
echo "Comparing categories"
compare_alpha_diversity.py \
--method anosim \
-i /home/cbmucl06/Combo_analysis/Beta_analysis/weighted_unifrac_dm.txt \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-c SampleSite \
-o /home/cbmucl06/Combo_analysis/Beta_analysis/Compare_cats_anosim_uwunifrac

echo "Comparing categories...completed."
