#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compare alpha diversity
echo "Comparing alpha diversity"
compare_alpha_diversity.py \
-i /home/cbmucl06/Combo_analysis/Alpha_analysis/Collated_alpha_analysis_e4284/chao1.txt \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-c SampleSite \
-o /home/cbmucl06/Combo_analysis/Alpha_analysis/Nonparam_compare_alpha_chao1

echo "Comparing alpha diversity...completed."
