#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute core microbiome
echo "Computing core microbiome"
compute_core_microbiome.py \
-i ~/Merged_analysis/chimsingleton_free_merged_OTU_table.biom \
-o ~/Merged_analysis/Core_microbiome_organic \
--min_fraction_for_core 0.9 \
--num_fraction_for_core_steps 20 \
--mapping_fp /home/cbmucl06/Raw_data/merged_map.tsv \
--valid_states "SampleSite:Organic" 

echo "Computing core microbiome... complete!"

#Deactivating environment
source deactivate
