#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Analyse core Diversity
echo "Analysing core diversity"
core_diversity_analyses.py \
-i /home/cbmucl06/Close_ref_otus_chimerafree/CSS_normalized_otu_table.biom \
-o ~/Close_ref_otus_chimerafree/CDA_normalized \
-e 1691 \
-t ~/SILVA_database/97_otus.tre \
-m ~/2018_02_smb/map_complete.tsv \
-a \
-O 24
echo "Analysing core diversity... Complete!"

#Deactivating environment
source deactivate
