#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Analyse core Diversity
echo "Analysing core diversity"
core_diversity_analyses.py \
-i /home/cbmucl06/TRUNCATED/Chimerafree_truncated_farm_cloref_OTUs_SILVA/singletonchimfree_truncated_farm_otu_table.biom \
-o /home/cbmucl06/TRUNCATED/Chimerafree_truncated_farm_cloref_OTUs_SILVA/ \
-e 4729 \
-t ~/SILVA_database/97_otus.tre \
-m /home/cbmucl06/Raw_data/Farm_data/farm_mapping.tsv \
-a \
-O 24
echo "Analysing core diversity... Complete!"

#Deactivating environment
source deactivate
