#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Analyse core Diversity
echo "Analysing core diversity"
core_diversity_analyses.py \
-i /home/cbmucl06/Merged_analysis/chimsingleton_free_merged_OTU_table.biom \
-o /home/cbmucl06/Merged_analysis/CDA_e3361 \
-e 3361 \
-t ~/SILVA_database/97_otus.tre \
-m /home/cbmucl06/Raw_data/merged_map.tsv \
-a \
-O 24
echo "Analysing core diversity... Complete!"

#Deactivating environment
source deactivate
