#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute core microbiome
echo "Computing core microbiome"
compute_core_microbiome.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom \
-o /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/core_microbiome_025
--min_fraction_for_core 0.25 \
--max_fraction_for_core 0.25 \
--mapping_fp /home/cbmucl06/Raw_data/merged_map_no_conv.tsv

echo "Computing core microbiome... complete!"

#Deactivating environment
source deactivate
