#!/bin/bash
#SBATCH -t 0:10:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Count sequences
echo "Counting sequences"
count_seqs.py \
-i /home/cbmucl06/Combo_analysis/Chimeric_seqs/chimeras.txt \
-o ~/Combo_analysis/comboseq_counts.txt

echo "Counting sequences... complete!"

#Deactivating environment
source deactivate
