#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Convert FASTQ to FASTA
echo "Converting FASTQ to FASTA"
convert_fastaqual_fastq.py \
-f /home/cbmucl06/Farm_data/organic_farm_data.fastq \
-o /home/cbmucl06/Farm_data/FASTA_files \
-c fastq_to_fastaqual

#Deactivating environment
source deactivate
