#!/bin/bash
#SBATCH -t 00:30:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Convert FASTQ to FASTA
echo "Converting FASTQ to FASTA"
convert_fastaqual_fastq.py \
-f /home/cbmucl06/Raw_data/Farm_data/Compost_samples/comp-org-s3.fastq \
-o /home/cbmucl06/Farm_data/FASTA_comp_conv-s1 \
-c fastq_to_fastaqual

#Deactivating environment
source deactivate
