#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Calculate differential abundance
echo "Calculating differential abundance"
differential_abundance.py \
--input_path /home/cbmucl06/Merged_analysis/scf_merged_otu_table.from_txt_json.biom \
--out_path /home/cbmucl06/Merged_analysis/diff_abundance_otus.txt \
--mapping_file_path /home/cbmucl06/Raw_data/merged_map.tsv \
--algorithm DESeq2_nbinom \
--mapping_file_category SampleSite \
--mapping_file_subcategory_1 Park \
--mapping_file_subcategory_2 Organic \
--DESeq2_diagnostic_plots

echo "Calculating differential abundance... Complete!"

#Deactivating environment
source deactivate
