#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Generate distance comparison plots
echo "Generating distance comparison plots"
make_distance_comparison_plots.py  \
-d /home/cbmucl06/Combo_analysis/Beta_analysis/bray_curtis_dm.txt \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-f "SampleSite" \
-c "Organic,Park" \
--save_raw_data \
-n 999 \
-o /home/cbmucl06/Combo_analysis/Beta_analysis/Statistical_analysis/Distance_comparison_plots

echo "Generating distance comparison plots...completed."
