#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter alignment
echo "Filtering alignment"
filter_alignment.py \
-i /home/cbmucl06/Combo_analysis/Aligned_rep_set_combo_pynast/combo_rep_set_aligned.fasta \
-o /home/cbmucl06/Combo_analysis/Aligned_rep_set_combo_pynast/Filtered_alignment \
--suppress_lane_mask_filter \
-g 0.80 \
-e 0.1

echo "Filtering alignment...completed."
