#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter FASTA
echo "Filtering FASTA"
filter_fasta.py \
-f ~/Combo_analysis/combo_rep_set.fna \
-o ~/Combo_analysis/filtered_combo_rep_set.fna \
-b ~/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom

echo "Filtering FASTA...completed."
