#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter outlier samples
echo "Filtering outlier samples "
filter_samples_from_otu_table.py \
-i ~/Merged_analysis/chimsingleton_free_merged_OTU_table.biom \
-o ~/Merged_analysis_org_only/chimsingleton_free_merged_OTU_table.biom \
-m ~/Raw_data/merged_map.tsv \
--output_mapping_fp ~/Raw_data/merged_map_no_conv.tsv \
-s 'SampleSite:*,!Conventional'

#Deactivating environment
source deactivate
