#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter singletons
echo "Filtering singletons"
filter_otus_from_otu_table.py \
-i /home/cbmucl06/Chimerafree_combo_picked_OTUs_PICRUSt_new/singout_filt_otu_table.biom \
-o /home/cbmucl06/Chimerafree_combo_picked_OTUs_PICRUSt_new/filt_2_otu_table.biom \
--min_count_fraction 0.00005 

source deactivate
