#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter outlier samples
echo "Filtering outlier samples "
filter_samples_from_otu_table.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/otu_table.biom \
-o /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_2_otu_table.biom \
-n 4000 \
-x 210000

#Deactivating environment
source deactivate
