#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Filter chimeric sequences
echo "Filtering chimeras"
filter_fasta.py \
-f /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/seqs_rc.fna \
-o /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/chimera_free_farm_seqs.fna \
-s /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/Chimera_analysis/chimeras.txt \
-n

echo "Filtering fasta sequences...completed."
