#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute group significance
echo "Computing group significance"
group_significance.py \
-i /home/cbmucl06/Combo_analysis/PICRUSt_analysis/PICRUSt_highlev_BIOM.biom \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-o /home/cbmucl06/Combo_analysis/PICRUSt_analysis/nonparam_hilev.txt \
-c SampleSite \
-s nonparametric_t_test 

echo "Computing group significance...completed."
