#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Identify chimeric sequences
echo "Identifying chimeric sequences"
identify_chimeric_seqs.py \
-m usearch61 \
-i /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/seqs_rc.fna \
-o /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/farm_chimeric_seqs.fna \
--reference_seqs_fp ~/SILVA_database/silva_132_97_16S.fna 

echo "Identifying chimeric sequences... Completed"

#Deactivating environment
source deactivate
