#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Identify chimeric sequences
echo "Identifying chimeric sequences"
parallel_identify_chimeric_seqs.py \
-m ChimeraSlayer \
-i ~/Close_ref_otus_Q25_contax7/closeq25_rep_sets.fasta \
-o ~/Close_ref_otus_Q25_contax7/closeq25_chimeric_seqs.txt \
-a ~/SILVA_database/97_alignment.fna \
-O 24
-T

echo "Identifying chimeric sequences... Completed"

#Deactivating environment
source deactivate
