#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Identify chimeric sequences with Chimera Slayer
echo "Identifying chimeric sequences with ChimeraSlayer"
parallel_identify_chimeric_seqs.py \
-i ~/Picked_OTUs/Close_ref_otus_Q25_contax7/ \
-o ~/Picked_OTUs/Close_ref_otus_Q25_contax7/chimeric_seqs_chimslayer.txt \
-a ~/SILVA_database/97_alignment.fna \
-r ~/SILVA_database/silva_132_97_16S.fna \
-O 24

echo "Identifying chimeric sequences... Completed"

#Deactivating environment
source deactivate
