#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Identify chimeric sequences with ChimeraSlayer
echo "Identifying chimeric with ChimeraSlayer"
parallel_identify_chimeric_seqs.py \
-m usearch61 \
-i ~/Demultiplexed/Split_libraries_Q25/seqs.fna \
-o ~/Picked_OTUs/Close_ref_otus_Q25_contax7/chimeric_seqs_usearch.txt \
--reference_seqs_fp ~/SILVA_database/silva_132_97_16S.fna \
--usearch61_minh 0.3 \
--usearch61_mindiffs 3 \
--usearch61_mindiv 1 \
--usearch61_xn 5 

echo "Identifying chimeric sequences... Completed"

#Deactivating environment
source deactivate
