#!/bin/bash
#SBATCH -t 2:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Compute jackknifed beta diversity
echo "Computing jackknifed beta diversity"
jackknifed_beta_diversity.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom \
-o /home/cbmucl06/Combo_analysis/Beta_analysis/Jackknifed_beta_diversity \
-m ~/Raw_data/merged_map_no_conv.tsv \
-e 4284 \
-t /home/cbmucl06/Combo_analysis/Composition_analysis/combo_filtered_rep_phylogeny.tre \
-a \
-O 24

#Deactivating environment
source deactivate
