#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Plot alpha Rarefaction
echo "Plotting alpha rarefactions"
make_rarefaction_plots.py \
-i ~/Combo_analysis/Alpha_analysis/Collated_alpha_e4141 \
-o ~/Combo_analysis/Alpha_analysis/Results/Alpha_plots_e4141 \
--generate_average_tables \
-m ~/Raw_data/merged_map_no_conv.tsv

#Deactivating environment
source deactivate
