#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Plot alpha Rarefaction
echo "Plotting alpha rarefactions"
make_rarefaction_plots.py \
-i /home/cbmucl06/Close_ref_otus_chimerafree/Results/Collated_alpha_analysis \
-o /home/cbmucl06/Close_ref_otus_chimerafree/Results/Alpha_plots \
-m ~/2018_02_smb/map_complete.tsv \
-g pdf \
--generate_average_tables

#Deactivating environment
source deactivate
