#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Generate 2D PCoA plots
echo "Generating 2D PCoA plots"
make_2d_plots.py \
-i /home/cbmucl06/Combo_analysis/Beta_analysis/weighted_unifrac_pc.txt \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-b "SampleSite" \
-o /home/cbmucl06/Combo_analysis/Beta_analysis/2D_PCoA_wunifrac

echo "Generating 2D PCoA plots...completed."
