#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Make tree
echo "Making tree"
make_phylogeny.py \
-i /home/cbmucl06/Combo_analysis/Aligned_filtered_combo_rep_set/Filtered_alignment/filtered_combo_rep_set_aligned_pfiltered.fasta \
-o /home/cbmucl06/Combo_analysis/Composition_analysis/combo_filtered_rep_phylogeny.tre

echo "Making tree...completed."
