#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2

#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Merge OTU tables
echo "Merging OTU tables"
merge_otu_tables.py \
-i /home/cbmucl06/Chimerafree_Farm_cloref_OTUs_SILVA/singletonchimfree_farm_otu_table.biom,/home/cbmucl06/Chimerafree_cloref_OTUs_SILVA/outliersingletonfree_otu_table.biom \
-o /home/cbmucl06/chimsingleton_free_merged_OTU_table.biom \

echo "Merging OTU tables... Complete!"

#Deactivating environment
source deactivate
