#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Multiple Rarefaction
echo "Creating Multiple rarefactions"
parallel_multiple_rarefactions.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom \
-o /home/cbmucl06/Combo_analysis/Alpha_analysis/Rarefied_tables_e4141 \
-m 9 \
-x 4284 \
-s 285 \
-n 30 \
-O 24

#Deactivating environment
source deactivate
