#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Multiple Rarefaction
echo "Creating Multiple rarefactions"
parallel_multiple_rarefactions.py \
-i /home/cbmucl06/Close_ref_otus_chimerafree/outliersingletonfree_otu_table.biom \
-o /home/cbmucl06/Close_ref_otus_chimerafree/Rarefied_otu_tables \
-m 0 \
-x 120000 \
-s 20000 \
-n 50 \
-O 24

#Deactivating environment
source deactivate
