#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
module load R
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Normalise table
echo "Normalizing OTU table"
normalize_table.py \
-i ~/Close_ref_otus_chimerafree \
-a CSS \
-o ~/Close_ref_otus_chimerafree/CSS_normalized_otu_table.biom 

#Deactivating environment
source deactivate
