#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
module load R
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Normalise table
echo "Normalizing OTU table"
normalize_table.py \
-i /home/cbmucl06/Farm_cloref_OTUs_SILVA/otu_table.biom \
-a CSS \
-o /home/cbmucl06/Farm_cloref_OTUs_SILVA/CSS_normalized_farm_otu_table.biom 

#Deactivating environment
source deactivate
