#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
module load R
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Generate heatmap
echo "Generating OTU heatmap"
make_otu_heatmap.py \
-i ~/Combo_analysis/PICRUSt_analysis/PICRUSt_output_high_rarefied.biom \
-o ~/Combo_analysis/PICRUSt_analysis/heatmap.pdf \
-m ~/Raw_data/merged_map_no_conv.tsv \
-c SampleSite

#Deactivating environment
source deactivate
