#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
module load R
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Generate heatmap
echo "Generating OTU heatmap"
make_otu_heatmap.py \
-i /home/cbmucl06/Merged_analysis/BIOM_tables/chimsingleton_free_merged_OTU_table.biom \
-o /home/cbmucl06/Merged_analysis/heatmap.pdf \
-t ~/SILVA_database/97_otus.tre \
-m ~/Raw_data/merged_map_no_conv.tsv \
-c SampleSite

#Deactivating environment
source deactivate
