#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Generate heatmap
echo "Generating OTU heatmap"
make_otu_heatmap.py \
-i ~/Picked_OTUs/Close_ref_otus_Q25_contax7/otu_table.biom \
-o ~/Picked_OTUs/Close_ref_otus_Q25/OTU_heatmap.png \
-t ~/SILVA_database/97_otus.tre \
-m ~/2018_02_smb/map_complete.tsv \

#Deactivating environment
source deactivate
