#!/bin/bash
#SBATCH -t 01:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Picking OTUS (closed reference)
echo "Picking OTUS with closed reference"
pick_closed_reference_otus.py \
-i /home/cbmucl06/Demultiplexed/Split_libraries_Q25_farm/chimera_free_farm_seqs.fna \
-o ~/Chimerafree_Farm_cloref_OTUs_SILVA/ \
-r ~/SILVA_database/silva_132_97_16S.fna \
-t /home/cbmucl06/SILVA_database/Taxonomy_files/consensus_taxonomy_7_levels.txt \
--parallel \
-O 24

#Deactivating environment
source deactivate
