#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Pick representative set of sequences
echo "Picking representative set of sequences"
pick_rep_set.py \ 
-i /home/cbmucl06/Close_ref_otus_chimerafree/uclust_ref_picked_otus/seqs_chimeras_filtered_otus.txt \
--reference_seqs_fp ~/SILVA_database/silva_132_97_16S.fna \
-o /home/cbmucl06/Close_ref_otus_chimerafree/rep_seqs_chimera_otus.fna

#Deactivating environment
source deactivate
