#!/bin/bash
#SBATCH -t 3:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Picking OTUS (open reference)
echo "Picking OTUS with open reference"
pick_open_reference_otus.py \
-i ~/Demultiplexed/Split_libraries_Q25/seqs.fna \
-o ~/Open_ref_otus_Q25_s0001/ \
-r ~/SILVA_database/silva_132_97_16S.fna \
-a \
-O 24

#Deactivating environment
source deactivate
