#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Pick representative sets
echo "Picking repr sets"
pick_rep_set.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/uclust_ref_picked_otus/chimera_free_combo_seqs_otus.txt \
-o /home/cbmucl06/Combo_analysis/combo_rep_set.fna \
-r /home/cbmucl06/SILVA_database/silva_132_97_16S.fna

echo "Picking repr sets... complete!"

#Deactivating environment
source deactivate
