#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Picking OTUS (closed reference)
echo "Picking OTUS with closed reference"
pick_closed_reference_otus.py \
-i /home/cbmucl06/organic_farm_data.fastq \
-o ~/Close_ref_otus_organic/ \
-r ~/SILVA_database/silva_132_97_16S.fna \
-t ~/SILVA_database/Taxonomy_files/consensus_taxonomy_7_levels.txt \
-a \
-O 24

#Deactivating environment
source deactivate
