#!/bin/bash
#SBATCH -t 01:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Picking OTUS (closed reference)
echo "Picking OTUS with closed reference"
pick_closed_reference_otus.py \
-i /home/cbmucl06/Combo_analysis/chimera_free_combo_seqs.fna \
-o /home/cbmucl06/Chimerafree_combo_picked_OTUs_PICRUSt/ \
-p ~/Parameter_files/PICRUSt_pick_otus.txt \
-r /home/cbmucl06/GREENGENES_database/rep_set/97_otus.fasta \
-t /home/cbmucl06/GREENGENES_database/taxonomy/97_otu_taxonomy.txt \
--parallel \
-O 24

#Deactivating environment
source deactivate
