#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate my_root

#Determine alpha diversity
echo "Determining alpha diversity"
metagenome_contributions.py \
-i /home/cbmucl06/PICRUST_normalized_table.biom \
-o /home/cbmucl06/ko_metagenome_contributions.tab \
-t ko

#Deactivating environment
source deactivate
