#!/bin/bash
#SBATCH -t 01:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
export TMPDIR=~/qiime_tmp
source activate qiime1

#Plot Q scores
echo "Plotting Q scores"
quality_scores_plot.py \
-q /home/cbmucl06/Split_libraries_Q25_orgfarm/seqs.qual \
-o /home/cbmucl06/Split_libraries_Q25_orgfarm/Qual_scores_plot

#Deactivating environment
source deactivate
