#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Remove chimeric sequences
echo "Removing chimeric sequences"
filter_fasta.py \
-i ~/Close_ref_otus_Q25_contax7/closeq25_rep_sets.fasta \
-o ~/Close_ref_otus_Q25_contax7/closeq25_rep_sets_chimerafree.fasta \
-s ~/Close_ref_otus_Q25_contax7/closeq25_chimeric_seqs.txt \
--negate

#Deactivating environment
source deactivate
