#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Single Rarefaction
echo "Creating singe rarefaction"
single_rarefaction.py \
-i /home/cbmucl06/Chimerafree_combo_picked_OTUs_PICRUSt_new/filt_2_otu_table.biom \
-o /home/cbmucl06/Chimerafree_combo_picked_OTUs_PICRUSt_new/filtered_3_otu_single_rarefied_e4087.biom \
-d 4087

#Deactivating environment
source deactivate
