#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Single Rarefaction
echo "Creating singe rarefaction"
single_rarefaction.py \
-i /home/cbmucl06/Combo_analysis/PICRUSt_analysis/PICRUSt_output_highlev.biom \
-o /home/cbmucl06/Combo_analysis/PICRUSt_analysis/PICRUSt_output_high_rarefied.biom \
-d 5590398

#Deactivating environment
source deactivate
