#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Splitting libraries
echo "Split libraries"
multiple_split_libraries_fastq.py \
-i /home/cbmucl06/Farm_data/ \
-p ~/split_libs_param.txt \
-o ~/Split_libraries_Q25_farm

#Deactivating environment
source deactivate
