#!/bin/bash
#SBATCH -t 4:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Splitting libraries
echo "Split libraries"
split_libraries_fastq.py \
-i ~/SeqPrep_joined/seqprep_assembled.fastq.gz \
-b ~/SeqPrep_joined/seqprep_assembled.fastq_barcodes.fastq \
-o ~/Split_libraries_Q19 \
-m ~/2018_02_smb/map_complete.tsv \
-q 19 \
--store_qual_scores \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

#Deactivating environment
source deactivate
