#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Splitting libraries
echo "Split libraries"
split_libraries_fastq.py \
-i /home/cbmucl06/conv_s1.fastq \
--barcode_type not-barcoded \
--sample_ids conv1 \
-o ~/Split_Q25_conv1 \
--phred_offset 33 \
-q 24

#Deactivating environment
source deactivate
