#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Summarize taxa
echo "Summarizing taxa"
summarize_taxa.py \
-i /home/cbmucl06/Combo_analysis/Chimerafree_combo_picked_OTUs/filtered_3_otu_table.biom \
-L 2,3,4,5,6 \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-d '|' \
-o /home/cbmucl06/Combo_analysis/Summarized_taxa

echo "Summarizing taxa... complete!"

#Deactivating environment
source deactivate
