#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Summarize taxa
echo "Summarizing taxa and creating plots"
summarize_taxa_through_plots.py \
-i /home/cbmucl06/Close_ref_otus_chimerafree/outliersingletonfree_otu_table.biom \
-o /home/cbmucl06/Close_ref_otus_chimerafree/Summarized_taxa\

echo "Summarizing taxa and creating plots... complete!"
#Deactivating environment
source deactivate
