#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Summarize taxa
echo "Summarizing taxa and creating plots"
summarize_taxa_through_plots.py \
-i ~/Combo_analysis/PICRUSt_analysis/PICRUSt_output_high_rarefied.biom \
-o ~/Combo_analysis/PICRUSt_analysis/Summarize_KEGG_hilev_rarefied \
-p ~/Parameter_files/picrust.txt \
-m /home/cbmucl06/Raw_data/merged_map_no_conv.tsv \
-c SampleSite

echo "Summarizing taxa and creating plots... complete!"
#Deactivating environment
source deactivate
