#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Summarize taxa
echo "Summarizing taxa and creating plots"
summarize_taxa_through_plots.py \
-i /home/cbmucl06/Chimerafree_Farm_cloref_OTUs_SILVA/singletonchimfree_farm_otu_table.biom \
-o /home/cbmucl06/Chimerafree_Farm_cloref_OTUs_SILVA/Taxa_summary \
-m /home/cbmucl06/Raw_data/merged_map.tsv \
-c SampleSite

echo "Summarizing taxa and creating plots... complete!"
#Deactivating environment
source deactivate
