#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules and qiime
module load eb
module load Miniconda2
#Load virtual environment
source activate qiime1

export TMPDIR=~/qiime_tmp

#Truncate sequences
echo "Truncating sequences"
truncate_fasta_qual_files.py \
-f /home/cbmucl06/Split_libraries_Q25_qual/seqs.fna \
-q /home/cbmucl06/Split_libraries_Q25_qual/seqs.qual \
-b 263 \
-o ~/TRUNCATED/Park_truncated_seqs

echo "Truncating sequences... complete!"

#Deactivating environment
source deactivate
